project:
  type: website
  output-dir: _site

website:
  title: "ICA Report Project"
  navbar:
    background: light
    left:
      - href: index.qmd
        text: Home
      - href: methodology.qmd
        text: Methodology
      - href: key_files.qmd
        text: Key Files
      - text: About the Tech
        menu:
          - href: about_r.qmd
            text: What is R?
          - href: about_quarto.qmd
            text: What is Quarto?
          - href: about_latex.qmd
            text: What is LaTeX?
    tools:
      - icon: github
        menu:
          - text: Source Code
            href:  https://github.com/htevilili-1991/ica_docs
          - text: Report a Bug
            href:  https://github.com/htevilili-1991/ica_docs/issues/new
  page-footer:
    left: "Created by Herman Tevilili"
    center: "Â© 2025 ICA Report Project"
    right: "Powered by Quarto"
  

format:
  html:
    theme: lux
    css: styles.css
    toc: true
